### ISSUE TITLE
Drive: The Surprising Truth About What Motivates Us

### ISSUE THREAD

**Issue by davidsantoso** [davidsantoso/books#1]
https://www.amazon.com/Drive-Surprising-Truth-About-Motivates/dp/1594484805

**Comment by allcentury** [comment]
You might also like: https://www.amazon.com/Self-Driven-Child-Science-Giving-Control/dp/0735222517

**Comment by davidsantoso** [comment]
Thanks for the recommendation! Definitely looks interesting so I just added it to my backlog.

**Comment by davidsantoso** [comment]
Finally finished this one. A good book overall but also can't help but feel slightly underwhelmed. At times it felt like the whole book could have been half as long and said about the same thing. And it wasn't even a long book. I can see myself going back to reference a section or two in the future and I'd still recommend it for someone looking for some interesting pop psychology.
