### ISSUE TITLE
Bringing Up Bébé: One American Mother Discovers the Wisdom of French Parenting

### ISSUE THREAD

**Issue by davidsantoso** [davidsantoso/books#2]
https://www.amazon.com/Bringing-Up-Bébé-Discovers-Parenting/dp/1594203334

**Comment by allcentury** [comment]
This looks really interesting - added to my list

**Comment by davidsantoso** [comment]
I'm about halfway through and it's been good! Hoping I can take some of of it's ideas and actually follow through with them in about a month!

**Comment by davidsantoso** [comment]
Finished this one a while ago and forgot to update the board! Nice light-hearted read that can probably be summed up with the phrase, "just relax a bit".
